## Тема: Системы линейных уравнений, часть 1
### Задание 1
Решить систему уравнений методом Гаусса:
$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

$\begin{pmatrix}
\left.\begin{matrix}
&1 & 1 & -1 & -2 \\ 
&2 & 1 & -1 & 1 \\ 
&1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}\implies
\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}\implies
\begin{pmatrix}
\left.\begin{matrix}
2 & 1 & -1 & 1 \\ 
1 & 1 & -1 & -2 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
-2\\
0\\ 
4
\end{matrix}
\end{pmatrix}\implies
\begin{pmatrix}
\left.\begin{matrix}
2 & 1 & -1 & 1 \\ 
1 & 1 & -1 & -2 \\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
-2\\
0\\ 
4
\end{matrix}
\end{pmatrix}\implies$

$$\implies\begin{pmatrix}
\left.\begin{matrix}
2 & 1 & -1 & 1 \\ 
0 & \frac{1}{2} & -\frac{1}{2} & -\frac{5}{2} \\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
-2\\
1\\ 
4
\end{matrix}
\end{pmatrix}\implies
\begin{pmatrix}
\left.\begin{matrix}
1 & \frac{1}{2} & -\frac{1}{2} & \frac{1}{2} \\ 
0 & 1 & -1 & -5 \\ 
0 & 0 & 1 & -\frac{3}{2}
\end{matrix}\right|
\begin{matrix}
-1\\
2\\ 
-2
\end{matrix}
\end{pmatrix}$$

$\begin{cases}
    x_1 + \frac{1}{2} x_2 - \frac{1}{2} x_3 + \frac{1}{2} x_4 = -1 \\
    x_2 - x_3 - 5 x_4 = 2 \\
    x_3 - \frac{3}{2} x_4 = -2
\end{cases}\implies
\begin{cases}
    x_1 = -1 - \frac{1}{2} x_2 + \frac{1}{2} x_3 - \frac{1}{2} x_4\\
    x_2  = 2 + x_3 + 5 x_4 \\
    x_3 = -2 + \frac{3}{2} x_4
\end{cases}\implies
\begin{cases}
x_4 = c \\
x_3 = -2 +\frac{3}{2} c \\
x_2 = \frac{13}{2} c \\
x_1 = -2 - 3c
\end{cases}$

### Задание 2
Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$

б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$

в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

a) Запишем матрицу системы $
\begin{pmatrix}
3 & -1 & 1 & 4 \\
2 & -5 & -3 & -17 \\
1 & 1 & -1 & 0
\end{pmatrix}\implies
\begin{pmatrix}
1 & 1 & -1 & 0 \\
0 & -4 & -2 & 4 \\
0 & -7 & -1 & -17
\end{pmatrix}\implies
\begin{pmatrix}
1 & 1 & -1 & 0 \\
0 & -4 & -2 & 4 \\
0 & 0 & 2.5 & -24
\end{pmatrix}\implies
$ совместна, 1 решение

In [2]:
import numpy as np
from scipy import linalg

In [3]:
x = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
b = np.array([[4, -17, 0]])
A = np.append(x, b.T, axis=1)
np.linalg.matrix_rank(x) == np.linalg.matrix_rank(A), np.linalg.matrix_rank(x), np.linalg.matrix_rank(A)

(True, 3, 3)

$rankA=rank \tilde A=3\implies$  система определена, т. е. имеет единственное решение

In [4]:
np.linalg.solve(x, b[0])

array([1., 2., 3.])

б) Запишем матрицу системы $
\begin{pmatrix}
2 & -4 & 6 & 1 \\
1 & -2 & 3 & -2 \\
3 & -6 & 9 & 5
\end{pmatrix}\implies
\begin{pmatrix}
1 & -2 & 3 & -2 \\
2 & -4 & 6 & 1 \\
3 & -6 & 9 & 5
\end{pmatrix}\implies
\begin{pmatrix}
1 & -2 & 3 & -2 \\
0 & 0 & 0 & 5 \\
3 & -6 & 9 & 5
\end{pmatrix}\implies
0 \neq 5 \implies
$ несовместна


In [5]:
x = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
b = np.array([[1, -2, 5]])
A = np.append(x, b.T, axis=1)
np.linalg.matrix_rank(x) == np.linalg.matrix_rank(A), np.linalg.matrix_rank(x), np.linalg.matrix_rank(A)

(False, 1, 2)

$𝑟𝑎𝑛𝑘𝐴 < 𝑟𝑎𝑛𝑘\tilde A\implies$ система несовместна.

In [6]:
try:
    np.linalg.solve(x, b[0])
except np.linalg.LinAlgError:
    print('Система несовместна.')

Система несовместна.


в) Запишем матрицу системы $
\begin{pmatrix}
1 & 2 & 5 & 4 \\
3 & 1 & -8 & -2 
\end{pmatrix}\implies
\begin{pmatrix}
1 & 2 & 5 & 4 \\
0 & -5 & 7 & -14 
\end{pmatrix}\implies
$ r = 2, n = 4, совместна, бесконечное множество решений

In [7]:
x = np.array([[1, 2, 5], [3, 1, -8]])
b = np.array([[4, -2]])
A = np.append(x, b.T, axis=1)
np.linalg.matrix_rank(x) == np.linalg.matrix_rank(A) , np.linalg.matrix_rank(x), np.linalg.matrix_rank(A)

(True, 2, 2)

$rankA=rank \tilde A<3\implies$  система имеет бесконечное количество решений

### Задание 3
Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

In [8]:
x = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
b = np.array([[3, 2, 4, 1]])
A = np.append(x, b.T, axis=1)
np.linalg.matrix_rank(x) == np.linalg.matrix_rank(A), np.linalg.matrix_rank(x),np.linalg.matrix_rank(A) 

(True, 4, 4)

$rankA=rank \tilde A=4\implies$  система определена, т. е. имеет единственное решение

In [9]:
np.linalg.solve(x, b[0])

array([2.76666667, 0.3       , 1.33333333, 0.5       ])

### Задание 4
Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$
Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

$A^{-1} = \frac{1}{|A|}A_*^T$

In [10]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.linalg.matrix_rank(x)

2

$|A| = \begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = 2$

$
\begin{vmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{vmatrix} =
a \begin{vmatrix}
4 & 5 \\
7 & 8
\end{vmatrix} - b \begin{vmatrix}
1 & 2 \\
7 & 8
\end{vmatrix} + c \begin{vmatrix}
1 & 2 \\
4 & 5
\end{vmatrix} = -3a + 6b -3c = -a + 2b - c$

$-a + 2b - c = 0$

$c = 2b - a$

При любых соотношений $a$, $b$ и $c$, кроме $c = 2b - a$   𝑟𝑎𝑛𝑘𝐴 < 𝑟𝑎𝑛𝑘𝐴̃ ⟹  система несовместна.
Проверим:

In [11]:
a=1
b=2
c=2*b-a

In [12]:
x1 = np.array([[1, 2, 3, 1], [4, 5, 6, 2], [7, 8, 9, c]])
np.linalg.matrix_rank(x) == np.linalg.matrix_rank(x1), np.linalg.matrix_rank(x1)

(True, 2)

## Тема: Системы линейных уравнений, часть 2

### Задание 1
Решить систему уравнений методом Крамера:

а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$


а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

$detA=\begin{vmatrix}
1 & -2 \\ 
3 & -4
\end{vmatrix} = 2 \neq 0$

$detA_{1}=\begin{vmatrix}
1 & -2 \\
7 & -4
\end{vmatrix} = 10$

$detA_{2}=\begin{vmatrix}
1 & 1 \\ 
3 & 7
\end{vmatrix} = 4$

$x_{1} = \frac{detA_{1}}{detA} = \frac{10}{2}=5$

$x_{2} = \frac{detA_{2}}{detA} = \frac{4}{2}=2$

In [13]:
x = np.array([[1, -2], [3, -4]])
b = np.array([[1, 7]])
A = np.round(np.linalg.det(x))
x_1 = x.copy()
x_1[:,0] = b
A_1 = np.round(np.linalg.det(x_1))
x_2 = x.copy()
x_2[:,1] = b
A_2 = np.round(np.linalg.det(x_2))
A_1 / A, A_2 / A

(5.0, 2.0)

б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

$detA=\begin{vmatrix}
2 & -1 & 5 \\ 
1 & 1 & -3 \\
2 & 4 & 1
\end{vmatrix} = 43 \neq 0$

$detA_{1}=\begin{vmatrix}
10 & -1 & 5 \\ 
-2 & 1 & -3 \\
1 & 4 & 1
\end{vmatrix} = 86$

$detA_{2}=\begin{vmatrix}
2 & 10 & 5 \\ 
1 & -2 & -3 \\
2 & 1 & 1
\end{vmatrix} = -43$

$detA_{3}=\begin{vmatrix}
2 & -1 & 10 \\ 
1 & 1 & -2 \\
2 & 4 & 1
\end{vmatrix} = 43$

$x_{1} = \frac{detA_{1}}{detA} = \frac{86}{43}=2$

$x_{2} = \frac{detA_{2}}{detA} = \frac{-43}{43}=-1$

$x_{3} = \frac{detA_{3}}{detA} = \frac{43}{43}=1$

In [14]:
x = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b = np.array([[10, -2, 1]])
A = np.round(np.linalg.det(x))
x_1 = x.copy()
x_1[:,0] = b
A_1 = np.round(np.linalg.det(x_1))
x_2 = x.copy()
x_2[:,1] = b
A_2 = np.round(np.linalg.det(x_2))
x_3 = x.copy()
x_3[:,2] = b
A_3 = np.round(np.linalg.det(x_3))
A_1 / A, A_2 / A, A_3 / A

(2.0, -1.0, 1.0)

### Задание 2
Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

а)$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$

б)$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$

а)$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$

$U = \begin{pmatrix}
3 & 26 & 30 \\
2 & 9 & 12 \\ 
1 & 2 & 4 \\ 
\end{pmatrix}$

$L = \begin{pmatrix} 
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{pmatrix}$

$U = \begin{pmatrix}
3 & 26 & 30 \\
0 & - \frac{25}{3} & -8 \\ 
0 & -\frac{20}{3} & -6 \\ 
\end{pmatrix}\implies
\begin{pmatrix}
3 & 26 & 30 \\
0 & -8 \frac{1}{3} & -8 \\ 
0 & 0 & \frac{2}{5} \\ 
\end{pmatrix}$

$L = \begin{pmatrix} 
1 & 0 & 0 \\
\frac{2}{3} & 1 & 0 \\
\frac{1}{3} & \frac{4}{5} & 1
\end{pmatrix}$


In [15]:
A = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
P, L, U = linalg.lu(A)

In [16]:
U,L

(array([[ 3.        , 26.        , 30.        ],
        [ 0.        , -8.33333333, -8.        ],
        [ 0.        ,  0.        ,  0.4       ]]),
 array([[1.        , 0.        , 0.        ],
        [0.66666667, 1.        , 0.        ],
        [0.33333333, 0.8       , 1.        ]]))

б)$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$

$U = \begin{pmatrix}
4 & 22 & 53 & 33 \\
2 & 5 & 8 & 9 \\ 
3 & 18 & 29 & 18 \\
1 & 1 & 2 & 4
\end{pmatrix}\implies
\begin{pmatrix}
4 & 22 & 53 & 33 \\
0 & -6 & -18 \frac{1}{2} & -7 \frac{1}{2} \\ 
0 & 1 \frac{1}{2} & -10 \frac{3}{4} & -6 \frac{3}{4} \\
0 & -4 \frac{1}{2} & -11 \frac{1}{4} & -4 \frac{1}{4} 
\end{pmatrix}\implies
\begin{pmatrix}
4 & 22 & 53 & 33 \\
0 & -6 & -18 \frac{1}{2} & -7 \frac{1}{2} \\ 
0 & 1 \frac{1}{2} & -10 \frac{3}{4} & -6 \frac{3}{4} \\
0 & -4 \frac{1}{2} & -11 \frac{1}{4} & -4 \frac{1}{4} 
\end{pmatrix}\implies
\begin{pmatrix}
4 & 22 & 53 & 33 \\
0 & -6 & -18 \frac{1}{2} & -7 \frac{1}{2} \\ 
0 & 0 & -15 \frac{3}{8} & -8 \frac{5}{8} \\
0 & 0 & 2 \frac{5}{8} & 1 \frac{3}{8} 
\end{pmatrix}$
$U = \begin{pmatrix}
4 & 22 & 53 & 33 \\
0 & -6 & -18 \frac{1}{2} & -7 \frac{1}{2} \\ 
0 & 0 & -15 \frac{3}{8} & -8 \frac{5}{8} \\
0 & 0 & 0 & - \frac{4}{41}
\end{pmatrix}$

$L = \begin{pmatrix} 
1 & 0 & 0 & 0 \\
\frac{1}{2} & 1 & 0 & 0 \\
\frac{3}{4} & -\frac{1}{4} & 1 & 0 \\
\frac{1}{4} & \frac{3}{4} & - \frac{7}{41} & 1
\end{pmatrix}$

In [17]:
A = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])
P, L, U = linalg.lu(A)
U, L

(array([[  4.        ,  22.        ,  53.        ,  33.        ],
        [  0.        ,  -6.        , -18.5       ,  -7.5       ],
        [  0.        ,   0.        , -15.375     ,  -8.625     ],
        [  0.        ,   0.        ,   0.        ,  -0.09756098]]),
 array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.5       ,  1.        ,  0.        ,  0.        ],
        [ 0.75      , -0.25      ,  1.        ,  0.        ],
        [ 0.25      ,  0.75      , -0.17073171,  1.        ]]))

## Задание 3
Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

$U = \begin{pmatrix}
11 & 7 & 5 \\
9 & 8 & 4 \\
2 & 1 & 3
\end{pmatrix}\implies
\begin{pmatrix}
11 & 7 & 5 \\
0 & \frac{25}{11} & - \frac{1}{11} \\
0 & - \frac{3}{11} & \frac{23}{11}  
\end{pmatrix}\implies
\begin{pmatrix}
11 & 7 & 5 \\
0 & \frac{25}{11} & - \frac{1}{11} \\
0 & 0 & \frac{52}{25}  
\end{pmatrix}$

$L = \begin{pmatrix} 
1 & 0 & 0 \\
\frac{9}{11} & 1 & 0 \\
\frac{2}{11} & - \frac{3}{25} & 1
\end{pmatrix} $

$\begin{cases}
y_{1} = -6 \\
\frac{9}{11} y_{1} + y_{2} =-5 \\
\frac{2}{11}y_{1} - \frac{3}{25} y_{2} + y_{3} = 1
\end{cases}\implies
\begin{cases} y_{1} = -6\\
y_{2} = -\frac{1}{11}\\
y_{3} = \frac{52}{25}
\end{cases}
$

$Ux=y:\begin{cases}
11x_{1} + 7x_{2} + 5x_{3} = -6, \\
\frac{25}{11} x_{2} - \frac{1}{11} x_{3}= - \frac{1}{11}, \\
\frac{52}{25} x_{3} = \frac{52}{25}
\end{cases}\implies
\begin{cases}
x_{1} = -1\\
x_{2} = 0\\
x_{3} = 1
\end{cases}$

In [18]:
x_1=-1
x_2=0
x_3=1
2*x_1+x_2+3*x_3, 11*x_1+7*x_2+5*x_3, 9*x_1+8*x_2+4*x_3

(1, -6, -5)

In [19]:
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
b = np.array([1, -6, -5])
P, L, U = linalg.lu(A)
U, L

(array([[11.        ,  7.        ,  5.        ],
        [ 0.        ,  2.27272727, -0.09090909],
        [ 0.        ,  0.        ,  2.08      ]]),
 array([[ 1.        ,  0.        ,  0.        ],
        [ 0.81818182,  1.        ,  0.        ],
        [ 0.18181818, -0.12      ,  1.        ]]))

In [20]:
lu, piv = linalg.lu_factor(A)
x = linalg.lu_solve((lu, piv), b)
print(f' x_1 = {x[0]:.02f}; x_2 = {x[1]:.02f}; x_3 = {x[2]:.02f}')

 x_1 = -1.00; x_2 = 0.00; x_3 = 1.00


### Задание 4
Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

$\begin{pmatrix}
81 & -45 & 45 \\
-45 & 50 & -15 \\
45 & -15 & 38
\end{pmatrix}$

$l_{11} =\sqrt{a_{11}} = \sqrt{81} = 9$

$l_{21} =\frac{a_{21}}{l_{11}} = \frac{-45}{9} = -5$

$l_{31} =\frac{a_{31}}{l_{11}} = \frac{45}{9} = 5$

$l_{22} = \sqrt{a_{22}-l_{21}^{2}} = \sqrt{50 - (-5)^2} = 5$

$l_{32} = \frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right) = \frac{1}{5}(-15 - (-5) \cdot 5) = 2$

$l_{33} = \sqrt{a_{33}-l_{32}^{2}-l_{31}^{2}} = \sqrt{38 - 2^2 - 5^2} = 3$

$L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}, 
\; \; 
L^{T} = \begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2\\ 
0 & 0 & 3
\end{pmatrix}.$

$Ly=b:\begin{cases}
    9 y_1 = 531 \\
    -5 y_1 + 5 y_2 = -460 \\
    5 y_1 + 2 y_2 + 3 y_3 = 193
\end{cases}\implies
\begin{cases}
y_1 = 59\\
y_2 = -33\\
y_3 = -12\end{cases}
$

$L^{T}x=y:\begin{cases}
    9 x_1 - 5 x_2 + 5 x_3 = 59 \\
    5 x_2 + 2 x_3 = -33 \\
    3 x_3 = -12
\end{cases}\implies
\begin{cases}
x_1 = 6\\
x_2 = -5\\
x_3 = -4
\end{cases}$

In [21]:
x_1=6
x_2=-5
x_3=-4
81*x_1-45*x_2+45*x_3, -45*x_1+50*x_2-15*x_3, 45*x_1-15*x_2+38*x_3

(531, -460, 193)

In [22]:
A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
L = np.linalg.cholesky(A)
L, L.T

(array([[ 9.,  0.,  0.],
        [-5.,  5.,  0.],
        [ 5.,  2.,  3.]]),
 array([[ 9., -5.,  5.],
        [ 0.,  5.,  2.],
        [ 0.,  0.,  3.]]))

### Задание 5 
Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ. (Метод Холецкого)

In [23]:
def M_choletsky(A):
    pivot = A[0, 0]
    b = np.mat(A[1:, 0])
    B = A[1:, 1:]
    return B - (b.T * b) / pivot


def L(A):
    n = A.shape[0]
    if n == 1:
        return np.sqrt(A)
    b = np.mat(A[1:, 0])
    pivot = np.sqrt(A[0, 0])
    return np.bmat([
        [np.mat(pivot), np.zeros((1, n - 1))],
        [b.T / pivot, L(M_choletsky(A))]
    ])


def __main():
   # A -> матрица А из 4 задания
    print(f'L=\n{L(A)} \n L(T)=\n{L(A).T}')


if __name__ == '__main__':
    __main()

L=
[[ 9.  0.  0.]
 [-5.  5.  0.]
 [ 5.  2.  3.]] 
 L(T)=
[[ 9. -5.  5.]
 [ 0.  5.  2.]
 [ 0.  0.  3.]]
