# Матрицы и матричные операции. Часть 1
### 1) Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:
а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;\
б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;\
в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;\
г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

а) $AB$, $BA$ - произведения матриц не определены\
б) $AB$ - матрица $2\times 3$
$BA$ - произведение матриц не определено\
в) $AB$ - матрица $8\times 8$
$BA$ - матрица $3\times 3$\
г) $AB$ - матрица $4\times 4$
$BA$ - матрица $4\times 4$

### 2) Найти сумму и произведение матриц $A=\begin{pmatrix}\
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [2]:
import numpy as np

In [4]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])
a + b, np.dot(a,b)

(array([[ 5, -3],
        [ 3,  5]]),
 array([[  4, -11],
        [ 12,  -3]]))

$$A + B = 
\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} + \begin{pmatrix}
4 & -1\\ 
0 &a 5
\end{pmatrix} = \begin{pmatrix}
1 + 4 & -2 + (-1) \\
3 + 0 & 0 + 5
\end{pmatrix} = \begin{pmatrix}
5 & -3 \\
3 & 5
\end{pmatrix}
$$

$$A \times B = 
\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} \times \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
1 \cdot 4 + (-2) \cdot 0 & 1 \cdot (-1) + (-2) \cdot 5 \\
3 \cdot (4) + 0 \cdot 0 & 3 \cdot (-1) + 0 \cdot 5
\end{pmatrix} = \begin{pmatrix}
4 & -11 \\
12 & -3
\end{pmatrix}
$$

### 3) Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$
3\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} -2 \begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix} + 4 \begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} =
\begin{pmatrix}
3 & 21 \\
9 & -18
\end{pmatrix} +
\begin{pmatrix}
0 & -10 \\
-4 & 2
\end{pmatrix} +
\begin{pmatrix}
8 & -16 \\
4 & 4
\end{pmatrix} =
\begin{pmatrix}
11 & -5 \\
9 & -12
\end{pmatrix}
$

In [6]:
a = np.array([[1,7], [3,-6]])
b = np.array([[0,5], [2,-1]])
c = np.array([[2,-4], [1,1]])
3*a -2*b + 4*c

array([[ 11,  -5],
       [  9, -12]])

###  4) Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$. Вычислить $AA^{T}$ и $A^{T}A$.

$$A^{T}=\begin{pmatrix}
4 & 5 & 2 \\
1 & -2 & 3
\end{pmatrix}$$$$A \times A^{T}=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} \times \begin{pmatrix}
4 & 5 & 2 \\
1 & -2 & 3
\end{pmatrix} = \begin{pmatrix} 
4 \cdot 4 + 1 \cdot 1 & 4 \cdot 5 + 1 \cdot (-2) & 4 \cdot 2 + 1 \cdot 3\\
5 \cdot 4 + (-2) \cdot 1 & 5 \cdot 5 + (-2) \cdot (-2) &  5 \cdot 2 + (-2) \cdot 3 \\
2 \cdot 4 + 3 \cdot 1 & 2 \cdot 5 + 3 \cdot (-2) & 2 \cdot 2 + 3 \cdot 3
\end{pmatrix} = \begin{pmatrix} 
17 & 18 & 11 \\
18 & 29 & 4 \\
11 & 4 & 13
\end{pmatrix}$$$$A^{T} \times A =  \begin{pmatrix}
4 & 5 & 2 \\
1 & -2 & 3
\end{pmatrix} \times \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} = \begin{pmatrix} 
4 \cdot 4 + 5 \cdot 5 + 2 \cdot 2 & 4 \cdot 1 + 5 \cdot (-2) + 2 \cdot 3 \\
1 \cdot 4 + (-2) \cdot 5 + 3 \cdot 2 & 1 \cdot 1 + (-2) \cdot (-2) + 3 \cdot 3
\end{pmatrix} = \begin{pmatrix} 
45 & 0 \\
0 & 14
\end{pmatrix}$$

In [8]:
a = np.array([[4, 1], [5, -2], [2, 3]])
np.dot(a, a.T), np.dot(a.T, a)

(array([[17, 18, 11],
        [18, 29,  4],
        [11,  4, 13]]),
 array([[45,  0],
        [ 0, 14]]))

### 5) Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [9]:
def matrix_dot(a, b):
    if len(a[0]) == len(b) and len(a) == len(b[0]):
        c = [[0 for _ in range(len(a))] for _ in range(len(b[0]))]
        for i in range(len(a)):
            for m in range(len(a[0])):
                for n in range(len(b[0])):
                    c[i][n] = a[i][m] * b[m][n] + c[i][n]
    return c

In [10]:
a = np.array([[1, 2, 2, 4, 5], [6, 7, 8, 9, 0], [1, 2, 3, 4, 5], [6, 7, 8, 9, 0], [0, 9, 8, 7, 6], [5, 4, 3, 2, 1], [0, 9, 8, 7, 6], [9, 8, 7, 5, 6], [4, 7, 9, 3, 4], [1, 3, 5, 3, 0]])
b = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [3, 3, 3, 3, 3, 3, 3, 3, 3, 3], [4, 4, 4, 4, 4, 4, 4, 4, 4, 4], [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [11]:
a.shape, b.shape

((10, 5), (5, 10))

In [12]:
matrix_dot(a, b)

[[52, 52, 52, 52, 52, 52, 52, 52, 52, 52],
 [80, 80, 80, 80, 80, 80, 80, 80, 80, 80],
 [55, 55, 55, 55, 55, 55, 55, 55, 55, 55],
 [80, 80, 80, 80, 80, 80, 80, 80, 80, 80],
 [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
 [35, 35, 35, 35, 35, 35, 35, 35, 35, 35],
 [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
 [96, 96, 96, 96, 96, 96, 96, 96, 96, 96],
 [77, 77, 77, 77, 77, 77, 77, 77, 77, 77],
 [34, 34, 34, 34, 34, 34, 34, 34, 34, 34]]

In [15]:
%%timeit
matrix_dot(a, b)

685 µs ± 27.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [13]:
np.dot(a, b)

array([[ 52,  52,  52,  52,  52,  52,  52,  52,  52,  52],
       [ 80,  80,  80,  80,  80,  80,  80,  80,  80,  80],
       [ 55,  55,  55,  55,  55,  55,  55,  55,  55,  55],
       [ 80,  80,  80,  80,  80,  80,  80,  80,  80,  80],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 35,  35,  35,  35,  35,  35,  35,  35,  35,  35],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 96,  96,  96,  96,  96,  96,  96,  96,  96,  96],
       [ 77,  77,  77,  77,  77,  77,  77,  77,  77,  77],
       [ 34,  34,  34,  34,  34,  34,  34,  34,  34,  34]])

In [14]:
%%timeit
np.dot(a, b)

2.88 µs ± 200 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## Матрицы и матричные операции. Часть 2
Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.
### 1) Вычислить определитель:

a)
$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$
б)
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
в)
$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$
а)$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = sinx \cdot sinx - (-cosx) \cdot cosx = 1$$
б) $$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 4 \cdot 5 \cdot 9 = 180$$

In [30]:
x=1
a=np.array([[np.sin(x),-1*np.cos(x)],[np.cos(x),np.sin(x)]])
np.linalg.det(a)

1.0

In [18]:
b = np.array([[4, 2, 3], [0, 5, 1], [0, 0,9]])
np.linalg.det(b)

180.0

в)$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = \begin{vmatrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & -6 & -12
\end{vmatrix} = 
\begin{vmatrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & 0 & 0
\end{vmatrix} = 0$$

In [25]:
c = np.array([[1, 2 ,3], [4, 5, 6], [7, 8, 9]])
print(f'|С| = {np.linalg.det(c):.5f}')

|С| = -0.00000


### 2) Определитель матрицы $A$ равен $4$. Найти:\
а) $det(A^{2})$;\
б) $det(A^{T})$;\
в) $det(2A)$.\

а) $det(A^{2}) = det(A \cdot A) = det(A) \cdot det(A) = 4 \cdot 4 = 16$;\
б) $det(A^{T})= det(A) = 4$;\
в) $det(2A) = 2^n \cdot det(A) = 2^n \cdot 4$, где $n$ размер матрицы.

### 3) Доказать, что матрица
$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
вырожденная.

$\det \begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix} = -2 (-182 - 42) - 7 (52 + 18) - 3 (28 - 42) = 0
$\
Матрица вырожденная, т.к. ее определитель равен нулю

In [33]:
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
np.linalg.det(a)

0.0

### 4) Найти ранг матрицы:
а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$
б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

а) вычтем из второй строки матрицы первую, получим\
$
\begin{pmatrix}
1 & 2 & 3 \\ 
0 & -1 & -2 \\ 
2 & 3 & 4
\end{pmatrix}
$
вычтем из третьей строки вторую, умноженную на 2\
$
\begin{pmatrix}
1 & 2 & 3 \\ 
0 & -1 & -2 \\ 
0 & -1 & -2
\end{pmatrix}
$
третью строку можно вычеркнуть и остается матрица ранга 2\
b) Переставим строки местами для удобства\
$\begin{pmatrix}
2 & 3 & 5 & 6 \\
0 & 0 & 2 & 1 \\ 
0 & 0 & 2 & 2 \\ 
0 & 0 & 4 & 3 
\end{pmatrix}$
вычтем из 4 строчки удвоенную вторую\
$\begin{pmatrix}
2 & 3 & 5 & 6 \\
0 & 0 & 2 & 1 \\ 
0 & 0 & 2 & 2 \\ 
0 & 0 & 0 & 1 
\end{pmatrix}$
вычтем из третьей строчки вторую\
$\begin{pmatrix}
2 & 3 & 5 & 6 \\
0 & 0 & 2 & 1 \\ 
0 & 0 & 0 & 1 \\ 
0 & 0 & 0 & 1 
\end{pmatrix}$
вычеркнем ненужную 4-ю строчку\
$\begin{pmatrix}
2 & 3 & 5 & 6 \\
0 & 0 & 2 & 1 \\ 
0 & 0 & 0 & 1
\end{pmatrix}$
ранг матрицы равен 3