In [1]:
import numpy as np

### Задание 1
Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}$$

Решение
$$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
b_1 \\
b_2
\end{pmatrix}=
\lambda\cdot
\begin{pmatrix}
b_1 \\
b_2
\end{pmatrix}$$
$
\begin{cases}
-b_1 - 6b_2 = \lambda b_1 \\
2b_1 + 6b_2 = \lambda b_2
\end{cases}
\implies
\begin{cases}
b_1 = -\frac{6b_2}{\lambda + 1} \\
-\frac{12b_2}{\lambda + 1} + 6b_2 = \lambda b_2
\end{cases}
\implies
-12 + 6\lambda + 6 = \lambda^2 + \lambda
\implies
\lambda^2 - 5\lambda + 6 = 0
$
$$D = 25 - 24 = 1$$
$$
\lambda_1 = \frac{5 + 1}{2} = 3 \\
\lambda_2 = \frac{5 - 1}{2} = 2
$$

Подставим $\lambda_1$ в исходную систему уравнений 
$$\begin{cases}
(-1 - 3)b_1 - 6b_2 = 0 \\
2b_1 + (6 - 3)b_2 = 0 
\end{cases}\implies\begin{cases}
b_1 = -\frac{3}{2} b_2 \\
b_1 = -\frac{3}{2} b_2
\end{cases}\implies 
\begin{pmatrix} b_1 \\ b_2
\end{pmatrix}
\begin{pmatrix}
3 \\
-2
\end{pmatrix}$$

Подставим $\lambda_2$ в исходную систему уравнений
$$\begin{cases}
-b_1 - 6b_2 = 2 b_1 \\
2b_1 + 6b_2 = 2 b_2
\end{cases}\implies\begin{cases}
b_1 = -2b_2 \\
b_1 = -2b_2
\end{cases}
$$

In [4]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


### Задание 2
Дан оператор поворота на 180 градусов, задаваемый матрицей
$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}$$
Показать, что любой вектор является для него собственным.

Решение
$$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}
\begin{pmatrix} x ,\ y
\end{pmatrix}$$$
\lambda
\begin{pmatrix}
x \\
y\end{pmatrix}$$
\begin{cases}
-x = \lambda x \\
-y = \lambda y
\end{cases}
\implies
\lambda = -1
$
Любой вектор является собственным для A

In [6]:
a = np.array([[-1, 0], [0, -1]])
w, v = np.linalg.eig(a)
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1  0]
 [ 0 -1]]
Собственные значения:
[-1. -1.]
Собственные векторы:
[[1. 0.]
 [0. 1.]]


### Задание 3
Пусть линейный оператор задан матрицей
$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}$$
Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

Решение
$$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}\begin{pmatrix} 1 ,\ 1
\end{pmatrix}$$$
\lambda\begin{pmatrix}
1 \\
1
\end{pmatrix}
\begin{cases}
1 + 1 = \lambda \implies \lambda = 2 \\
-1 + 3 = \lambda \implies \lambda = 2
\end{cases}
$

Вектор  𝑥=(1,1)  является собственным вектором линейного оператора, заданного матрицей  𝐴 , и его собственное значение составляет  𝜆=2.

### Задание 4
Пусть линейный оператор задан матрицей
$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}$$
Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.


Решение

$
\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\cdot
\begin{pmatrix}
3 \\ 
-3 \\
-4
\end{pmatrix}
= \lambda
\begin{pmatrix}
3 \\ 
-3 \\
-4
\end{pmatrix}
$

$
\begin{cases}
-9 = 3\lambda \implies \lambda = -3 \\
9 = -3\lambda \implies \lambda = -3 \\
-12 = -4\lambda \implies \lambda = 3
\end{cases}
$

Вектор не является собственным вектором этого линейного оператора